const mongoose =require("mongoose")

const orderSchema=mongoose.Schema({
    envioInfo:{
        direccion:{
            type:String,
            require:true
        },
        ciudad:{
            type:String,
            require:true
        },
        telefono:{
            type:String,
            require:true
        },
        departamento:{
            type:String,
            require:true
        }

    },
    user:
    {
        type:mongoose.Schema.Types.ObjectId,
        require:true,
        ref:"auth"
    },
    items:[{
        nombre:{
            type:String,
            require:true
        },
        cantidad:{
            type:Number,
            require:true
        },
        imagen:{
            type:String,
            require:true
        },
        precio:{
            type:Number,
            require:true
        },
        producto:{
            type:mongoose.Schema.Types.ObjectId,
            require:true,
            ref:"productos"
        }
    }],
    pagoInfo:{
        id:{
            type:String
        },
        estado:{
            type:String
        }
    },
    fechaPago:{
        type:Date
    },
    precioItems:{
        type:Number,
        require:true,
        default: 0.0
    },
    precioImpuesto:{
        type:Number,
        require:true,
        default:0.0
    },
    precioEnvio:{
        type:Number,
        require:true,
        default:0.0
    },
    precioTotal:{
        type:Number,
        require:true,
        default:0.0
    },
    estado:{
        type:String,
        require:true,
        default:"Procesando"
    },
    fechaEnvio:{
        type:Date
    },
    fechaCreacion:{
        type:Date,
        default:Date.now
    }
})
module.exports=mongoose.model("order",orderSchema)